name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ghc-version: "8.10.7"
            cabal-flags: ""
          - ghc-version: "9.0.2"
            cabal-flags: ""
          - ghc-version: "9.2.8"
            cabal-flags: ""
          - ghc-version: "9.4.8"
            cabal-flags: ""
          - ghc-version: "9.6.7"
            cabal-flags: ""
          - ghc-version: "9.8.4"
            cabal-flags: ""
          - ghc-version: "9.10.3"
            cabal-flags: ""
          - ghc-version: "9.12.2"
            cabal-flags: ""
          - ghc-version: "9.14.1"
            # https://github.com/ekmett/tagged/issues/72
            cabal-flags: "--allow-newer=template-haskell"
    steps:
    - uses: actions/checkout@v4

    - name: Install cabal/ghc
      uses: haskell-actions/setup@v2
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc-version }}
        cabal-version: '3.16.1.0'
    
    - name: Generate freeze file
      run: |
        cabal update
        cabal configure --disable-optimization --enable-tests ${{matrix.cabal-flags}}
        cabal freeze
    
    - name: Cache cabal work
      uses: actions/cache@v4
      with:
        path: |
          dist-newstyle
          ${{ steps.setup-haskell.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ hashFiles('cabal.project.freeze', 'cabal.project.local') }}-cabal-install
    
    - name: Build dependencies
      run: |
        cabal build --only-dependencies
    
    - name: Build package
      run: |
        cabal build
        
    - name: Run tests
      run: |
        cabal test
